revert: set up with global unique id
Not the real issue of the Noder issue:

    ERROR: relation \"ent_types\" does not exist (SQLSTATE 42P01)

For now, we disable the Noder retrieval in
cc2d6d393042102ffa702a219f1b5a471f4d226c.

This reverts commit db56983ff5756fe687eb931cd3b6b43193fb4380.